export const HOME_ROUTE = '/'
export const BOOKING_ROUTE = '/idopontfoglalas'
export const OUR_WORKS_ROUTE = '/munkaink'
export const PRICES_ROUTE = '/arlista'
export const PRIVACY_POLICY_ROUTE = '/adatvedelmi-nyilatkozat'
export const TERMS_OF_USE_ROUTE = '/felhasznalasi-feltetelek'
