import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

import "./globals.css";
import { Toaster } from "react-hot-toast";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <Header />
        <Toaster />
        <div className="fixed top-0 left-0 -z-10 object-cover w-screen h-screen">
          <Image alt="" src="/site-bg.png" fill className="object-cover" />
        </div>
        {children}
        {/* <Footer /> */}
      </body>
    </html>
  );
}
